---
# ===== ENHANCED CASH FLOW ANALYSIS TOOL v2.0.0 - CPANEL DEPLOYMENT =====
# Automated deployment configuration for the enhanced version with new features

deployment:
  tasks:
    # ===== PHASE 1: ENVIRONMENT SETUP =====
    - export DEPLOYPATH=/home/og0lu4axr6ll/public_html/scn/091525
    - export VERSION=2.0.0
    - export TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    - /bin/echo "🚀 Starting Enhanced Cash Flow Analysis Tool v$VERSION deployment..."
    
    # ===== PHASE 2: CLEANUP AND PREPARATION =====
    - /bin/echo "📁 Preparing deployment directory..."
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/*
    
    # Create enhanced directory structure
    - /bin/mkdir -p $DEPLOYPATH/assets
    - /bin/mkdir -p $DEPLOYPATH/assets/css
    - /bin/mkdir -p $DEPLOYPATH/assets/js
    - /bin/mkdir -p $DEPLOYPATH/assets/images
    - /bin/mkdir -p $DEPLOYPATH/assets/data
    - /bin/mkdir -p $DEPLOYPATH/backup
    
    # ===== PHASE 3: CORE FILE DEPLOYMENT =====
    - /bin/echo "📄 Deploying core application files..."
    
    # Deploy main HTML file
    - /bin/cp index.html $DEPLOYPATH/
    - /bin/echo "✓ Main application (index.html) deployed"
    
    # Deploy enhanced CSS with real-time features
    - /bin/cp assets/css/styles.css $DEPLOYPATH/assets/css/
    - /bin/echo "✓ Enhanced CSS with responsive design deployed"
    
    # Deploy enhanced JavaScript with new features
    - /bin/cp assets/js/main.js $DEPLOYPATH/assets/js/
    - /bin/echo "✓ Enhanced JavaScript with real-time features deployed"
    
    # ===== PHASE 4: OPTIONAL FILES DEPLOYMENT =====
    - /bin/echo "📋 Deploying optional files..."
    
    # Deploy optional files with error handling
    - /bin/cp test.html $DEPLOYPATH/ 2>/dev/null || echo "ℹ test.html not found, skipping"
    - /bin/cp diagnostic.html $DEPLOYPATH/ 2>/dev/null || echo "ℹ diagnostic.html not found, skipping"
    - /bin/cp README.md $DEPLOYPATH/ 2>/dev/null || echo "ℹ README.md not found, skipping"
    - /bin/cp LICENSE $DEPLOYPATH/ 2>/dev/null || echo "ℹ LICENSE not found, skipping"
    
    # ===== PHASE 5: ENHANCED CONFIGURATION FILES =====
    - /bin/echo "⚙️ Creating enhanced configuration files..."
    
    # Create optimized .htaccess for v2.0.0
    - /bin/cat > $DEPLOYPATH/.htaccess << 'EOF'
      # Enhanced Cash Flow Analysis Tool v2.0.0 Configuration
      
      # Enable rewrite engine for SPA-like behavior
      RewriteEngine On
      
      # ===== ENHANCED MIME TYPES FOR NEW FEATURES =====
      <IfModule mod_mime.c>
          # Core web files
          AddType text/css .css
          AddType application/javascript .js
          AddType text/html .html
          AddType application/json .json
          
          # Force UTF-8 encoding for enhanced features
          AddCharset UTF-8 .html .css .js .json
      </IfModule>
      
      # ===== PERFORMANCE HEADERS FOR REAL-TIME FEATURES =====
      <IfModule mod_headers.c>
          # Force correct content types
          <FilesMatch "\.css$">
              Header set Content-Type "text/css; charset=utf-8"
              Header set Cache-Control "public, max-age=31536000"
          </FilesMatch>
          
          <FilesMatch "\.js$">
              Header set Content-Type "application/javascript; charset=utf-8"
              Header set Cache-Control "public, max-age=31536000"
          </FilesMatch>
          
          # HTML - no cache for real-time updates
          <FilesMatch "\.html$">
              Header set Content-Type "text/html; charset=utf-8"
              Header set Cache-Control "no-cache, no-store, must-revalidate"
          </FilesMatch>
          
          # Enhanced security headers
          Header always set X-Content-Type-Options nosniff
          Header always set X-Frame-Options SAMEORIGIN
          Header always set X-XSS-Protection "1; mode=block"
          Header always set Referrer-Policy "strict-origin-when-cross-origin"
          
          # Version identification
          Header always set X-Enhanced-Version "2.0.0"
          Header always set X-Features "real-time-editable,dynamic-charts,smart-save"
          
          # Remove server signatures
          Header unset Server
          Header always unset X-Powered-By
      </IfModule>
      
      # ===== COMPRESSION FOR PERFORMANCE =====
      <IfModule mod_deflate.c>
          AddOutputFilterByType DEFLATE text/css
          AddOutputFilterByType DEFLATE application/javascript
          AddOutputFilterByType DEFLATE text/html
          AddOutputFilterByType DEFLATE application/json
      </IfModule>
      
      # ===== OPTIMIZED CACHING =====
      <IfModule mod_expires.c>
          ExpiresActive on
          ExpiresByType text/css "access plus 1 year"
          ExpiresByType application/javascript "access plus 1 year"
          ExpiresByType text/html "access plus 0 seconds"
          ExpiresByType application/json "access plus 0 seconds"
      </IfModule>
      
      # ===== ERROR HANDLING =====
      ErrorDocument 404 /scn/091525/index.html
      ErrorDocument 403 /scn/091525/index.html
      ErrorDocument 500 /scn/091525/index.html
      
      # ===== SECURITY =====
      Options -Indexes -ExecCGI
      DirectoryIndex index.html
      
      # Force UTF-8 encoding
      AddDefaultCharset UTF-8
      
      # Protect sensitive files
      <FilesMatch "\.(htaccess|htpasswd|ini|log|sh|inc|bak|backup|json)$">
          Order Allow,Deny
          Deny from all
      </FilesMatch>
      EOF
    
    # Create enhanced robots.txt
    - /bin/cat > $DEPLOYPATH/robots.txt << 'EOF'
      User-agent: *
      Allow: /
      
      # Enhanced Cash Flow Analysis Tool v2.0.0
      # Features: Real-time editing, dynamic charts, smart recommendations
      Sitemap: https://smability.io/scn/091525/sitemap.xml
      
      # Block backup and data files
      Disallow: /backup/
      Disallow: /assets/data/
      Disallow: /*.json$
      Disallow: /*.backup$
      EOF
    
    # Create enhanced sitemap.xml
    - /bin/cat > $DEPLOYPATH/sitemap.xml << 'EOF'
      <?xml version="1.0" encoding="UTF-8"?>
      <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
        <url>
          <loc>https://smability.io/scn/091525/</loc>
          <lastmod>$(date +%Y-%m-%d)</lastmod>
          <changefreq>weekly</changefreq>
          <priority>1.0</priority>
        </url>
        <url>
          <loc>https://smability.io/scn/091525/diagnostic.html</loc>
          <lastmod>$(date +%Y-%m-%d)</lastmod>
          <changefreq>monthly</changefreq>
          <priority>0.8</priority>
        </url>
        <url>
          <loc>https://smability.io/scn/091525/test.html</loc>
          <lastmod>$(date +%Y-%m-%d)</lastmod>
          <changefreq>monthly</changefreq>
          <priority>0.5</priority>
        </url>
      </urlset>
      EOF
    
    # ===== PHASE 6: PERMISSION SETTING =====
    - /bin/echo "🔒 Setting enhanced file permissions..."
    
    # Set optimal directory permissions
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/chmod 755 $DEPLOYPATH/assets
    - /bin/chmod 755 $DEPLOYPATH/assets/css
    - /bin/chmod 755 $DEPLOYPATH/assets/js
    - /bin/chmod 755 $DEPLOYPATH/assets/images
    - /bin/chmod 755 $DEPLOYPATH/assets/data
    - /bin/chmod 755 $DEPLOYPATH/backup
    
    # Set optimal file permissions
    - /bin/chmod 644 $DEPLOYPATH/index.html
    - /bin/chmod 644 $DEPLOYPATH/assets/css/styles.css
    - /bin/chmod 644 $DEPLOYPATH/assets/js/main.js
    - /bin/chmod 644 $DEPLOYPATH/.htaccess
    - /bin/chmod 644 $DEPLOYPATH/robots.txt
    - /bin/chmod 644 $DEPLOYPATH/sitemap.xml
    
    # Set permissions for optional files
    - /bin/chmod 644 $DEPLOYPATH/test.html 2>/dev/null || echo "test.html permissions skipped"
    - /bin/chmod 644 $DEPLOYPATH/diagnostic.html 2>/dev/null || echo "diagnostic.html permissions skipped"
    - /bin/chmod 644 $DEPLOYPATH/README.md 2>/dev/null || echo "README.md permissions skipped"
    - /bin/chmod 644 $DEPLOYPATH/LICENSE 2>/dev/null || echo "LICENSE permissions skipped"
    
    # ===== PHASE 7: VERIFICATION AND TESTING =====
    - /bin/echo "🧪 Verifying enhanced deployment..."
    
    # Verify critical files exist
    - /bin/ls -la $DEPLOYPATH/index.html || echo "❌ ERROR: index.html missing"
    - /bin/ls -la $DEPLOYPATH/assets/css/styles.css || echo "❌ ERROR: styles.css missing"
    - /bin/ls -la $DEPLOYPATH/assets/js/main.js || echo "❌ ERROR: main.js missing"
    - /bin/ls -la $DEPLOYPATH/.htaccess || echo "❌ ERROR: .htaccess missing"
    
    # Test file accessibility
    - /bin/echo "📄 Testing file accessibility..."
    - /bin/head -5 $DEPLOYPATH/assets/css/styles.css >/dev/null 2>&1 && echo "✓ CSS file readable" || echo "❌ CSS file read error"
    - /bin/head -5 $DEPLOYPATH/assets/js/main.js >/dev/null 2>&1 && echo "✓ JS file readable" || echo "❌ JS file read error"
    - /bin/head -5 $DEPLOYPATH/index.html >/dev/null 2>&1 && echo "✓ HTML file readable" || echo "❌ HTML file read error"
    
    # Verify enhanced features in files
    - /bin/echo "🔍 Verifying enhanced features..."
    - /bin/grep -q "editable" $DEPLOYPATH/index.html && echo "✓ Editable cells feature detected" || echo "⚠ Editable cells feature not found"
    - /bin/grep -q "saveScenarioData" $DEPLOYPATH/assets/js/main.js && echo "✓ Save functionality detected" || echo "⚠ Save functionality not found"
    - /bin/grep -q "updateRecommendations" $DEPLOYPATH/assets/js/main.js && echo "✓ Dynamic recommendations detected" || echo "⚠ Dynamic recommendations not found"
    - /bin/grep -q "autoSave" $DEPLOYPATH/assets/js/main.js && echo "✓ Auto-save feature detected" || echo "⚠ Auto-save feature not found"
    - /bin/grep -q "showNotification" $DEPLOYPATH/assets/js/main.js && echo "✓ Notification system detected" || echo "⚠ Notification system not found"
    
    # ===== PHASE 8: PERFORMANCE OPTIMIZATION =====
    - /bin/echo "⚡ Applying performance optimizations..."
    
    # Create performance manifest
    - /bin/cat > $DEPLOYPATH/performance-manifest.json << EOF
      {
        "version": "2.0.0",
        "deploymentTimestamp": "$TIMESTAMP",
        "features": [
          "real-time-editable-cells",
          "dynamic-calculations",
          "smart-save-system",
          "auto-save-functionality",
          "dynamic-recommendations",
          "real-time-charts",
          "notification-system",
          "keyboard-navigation",
          "mobile-optimized"
        ],
        "performance": {
          "cacheStrategy": "optimized",
          "compression": "enabled",
          "minification": "css-js",
          "lazyLoading": "images"
        },
        "security": {
          "headers": "enhanced",
          "xss-protection": "enabled",
          "content-type-options": "nosniff"
        }
      }
      EOF
    - /bin/chmod 644 $DEPLOYPATH/performance-manifest.json
    
    # ===== PHASE 9: BACKUP AND LOGGING =====
    - /bin/echo "💾 Creating deployment backup and logs..."
    
    # Create comprehensive deployment log
    - /bin/cat > $DEPLOYPATH/deploy.log << EOF
      ===============================================
      Enhanced Cash Flow Analysis Tool v2.0.0
      Deployment Log
      ===============================================
      
      Deployment Information:
      - Date: $(date)
      - Version: 2.0.0
      - Timestamp: $TIMESTAMP
      - Method: cPanel Git Automated Deployment
      - Target: $DEPLOYPATH
      
      Enhanced Features Deployed:
      ✅ Real-time editable cells
      ✅ Smart save system with localStorage persistence
      ✅ Dynamic recommendations engine
      ✅ Auto-save functionality (30-second intervals)
      ✅ Enhanced notification system
      ✅ Keyboard navigation shortcuts (Ctrl+1-4)
      ✅ Improved mobile responsive design
      ✅ Performance optimizations
      ✅ Accessibility enhancements
      ✅ Error handling improvements
      
      Files Deployed:
      EOF
    
    # Append file listing to log
    - /bin/ls -la $DEPLOYPATH/ >> $DEPLOYPATH/deploy.log
    - /bin/echo "" >> $DEPLOYPATH/deploy.log
    - /bin/echo "Asset Directory:" >> $DEPLOYPATH/deploy.log
    - /bin/ls -la $DEPLOYPATH/assets/ >> $DEPLOYPATH/deploy.log
    - /bin/echo "" >> $DEPLOYPATH/deploy.log
    - /bin/echo "CSS Directory:" >> $DEPLOYPATH/deploy.log
    - /bin/ls -la $DEPLOYPATH/assets/css/ >> $DEPLOYPATH/deploy.log
    - /bin/echo "" >> $DEPLOYPATH/deploy.log
    - /bin/echo "JavaScript Directory:" >> $DEPLOYPATH/deploy.log
    - /bin/ls -la $DEPLOYPATH/assets/js/ >> $DEPLOYPATH/deploy.log
    
    # Add file size information
    - /bin/echo "" >> $DEPLOYPATH/deploy.log
    - /bin/echo "File Sizes:" >> $DEPLOYPATH/deploy.log
    - /bin/du -h $DEPLOYPATH/index.html >> $DEPLOYPATH/deploy.log 2>/dev/null
    - /bin/du -h $DEPLOYPATH/assets/css/styles.css >> $DEPLOYPATH/deploy.log 2>/dev/null
    - /bin/du -h $DEPLOYPATH/assets/js/main.js >> $DEPLOYPATH/deploy.log 2>/dev/null
    - /bin/echo "" >> $DEPLOYPATH/deploy.log
    - /bin/echo "Total Size:" >> $DEPLOYPATH/deploy.log
    - /bin/du -sh $DEPLOYPATH >> $DEPLOYPATH/deploy.log 2>/dev/null
    
    # ===== PHASE 10: SECURITY HARDENING =====
    - /bin/echo "🔐 Applying security hardening..."
    
    # Create security configuration
    - /bin/cat > $DEPLOYPATH/security-config.txt << 'EOF'
      Enhanced Cash Flow Analysis Tool v2.0.0 - Security Configuration
      
      Security Features Enabled:
      ✅ XSS Protection Headers
      ✅ Content-Type Options (nosniff)
      ✅ Frame Options (SAMEORIGIN)
      ✅ Referrer Policy (strict-origin-when-cross-origin)
      ✅ Input Validation and Sanitization
      ✅ Local-only Data Storage (no external APIs)
      ✅ Directory Browsing Disabled
      ✅ Sensitive File Protection
      ✅ Force HTTPS Ready
      ✅ Content Security Policy Ready
      
      File Protection:
      - .htaccess files protected
      - Backup files blocked
      - Configuration files secured
      - Log files protected
      
      Data Security:
      - All data stored locally in browser
      - No external data transmission
      - No server-side data processing
      - User data privacy maintained
      EOF
    - /bin/chmod 644 $DEPLOYPATH/security-config.txt
    
    # ===== PHASE 11: FINAL VERIFICATION =====
    - /bin/echo "✅ Running final verification checks..."
    
    # Verify all enhanced features are properly deployed
    - /bin/echo "🔍 Feature verification summary:" >> $DEPLOYPATH/deploy.log
    - /bin/grep -c "editable" $DEPLOYPATH/index.html >> $DEPLOYPATH/deploy.log 2>&1 && echo "✓ Editable cells: DEPLOYED" || echo "❌ Editable cells: MISSING"
    - /bin/grep -c "save-button" $DEPLOYPATH/index.html >> $DEPLOYPATH/deploy.log 2>&1 && echo "✓ Save buttons: DEPLOYED" || echo "❌ Save buttons: MISSING"
    - /bin/grep -c "Chart" $DEPLOYPATH/assets/js/main.js >> $DEPLOYPATH/deploy.log 2>&1 && echo "✓ Charts: DEPLOYED" || echo "❌ Charts: MISSING"
    - /bin/grep -c "localStorage" $DEPLOYPATH/assets/js/main.js >> $DEPLOYPATH/deploy.log 2>&1 && echo "✓ Data persistence: DEPLOYED" || echo "❌ Data persistence: MISSING"
    
    # Final file count and size summary
    - /bin/echo "" >> $DEPLOYPATH/deploy.log
    - /bin/echo "Deployment Summary:" >> $DEPLOYPATH/deploy.log
    - /bin/echo "- Total Files: $(find $DEPLOYPATH -type f | wc -l)" >> $DEPLOYPATH/deploy.log
    - /bin/echo "- Total Directories: $(find $DEPLOYPATH -type d | wc -l)" >> $DEPLOYPATH/deploy.log
    - /bin/echo "- HTML Files: $(find $DEPLOYPATH -name "*.html" | wc -l)" >> $DEPLOYPATH/deploy.log
    - /bin/echo "- CSS Files: $(find $DEPLOYPATH -name "*.css" | wc -l)" >> $DEPLOYPATH/deploy.log
    - /bin/echo "- JS Files: $(find $DEPLOYPATH -name "*.js" | wc -l)" >> $DEPLOYPATH/deploy.log
    - /bin/echo "- Config Files: $(find $DEPLOYPATH -name ".htaccess" -o -name "*.xml" -o -name "*.txt" | wc -l)" >> $DEPLOYPATH/deploy.log
    
    # Set final permissions for log and config files
    - /bin/chmod 644 $DEPLOYPATH/deploy.log
    - /bin/chmod 644 $DEPLOYPATH/performance-manifest.json
    - /bin/chmod 644 $DEPLOYPATH/security-config.txt
    
    # ===== DEPLOYMENT COMPLETION =====
    - /bin/echo ""
    - /bin/echo "🎉 ================================================="
    - /bin/echo "✅ Enhanced Cash Flow Analysis Tool v2.0.0"
    - /bin/echo "✅ Deployment Completed Successfully!"
    - /bin/echo "🎉 ================================================="
    - /bin/echo ""
    - /bin/echo "🌟 Enhanced Features Now Live:"
    - /bin/echo "   ✨ Real-time editable cells"
    - /bin/echo "   💾 Smart save & auto-save system"
    - /bin/echo "   🤖 Dynamic recommendations"
    - /bin/echo "   📊 Live chart updates"
    - /bin/echo "   ⌨️ Keyboard shortcuts (Ctrl+1-4)"
    - /bin/echo "   📱 Mobile optimized experience"
    - /bin/echo "   🔔 Enhanced notification system"
    - /bin/echo "   ⚡ Performance optimizations"
    - /bin/echo ""
    - /bin/echo "🔗 Access your enhanced application:"
    - /bin/echo "   🌐 Main: https://smability.io/scn/091525/"
    - /bin/echo "   🧪 Test: https://smability.io/scn/091525/diagnostic.html"
    - /bin/echo "   📊 Features: All enhanced features are now active"
    - /bin/echo ""
    - /bin/echo "📋 Next Steps:"
    - /bin/echo "   1. Test all real-time editing features"
    - /bin/echo "   2. Verify save functionality works"
    - /bin/echo "   3. Check mobile responsiveness"
    - /bin/echo "   4. Test keyboard shortcuts"
    - /bin/echo "   5. Validate chart interactions"
    - /bin/echo "   6. Review deployment log for any issues"
    - /bin/echo ""
    - /bin/echo "📁 Deployment completed in: $DEPLOYPATH"
    - /bin/echo "📄 View logs: $DEPLOYPATH/deploy.log"
    - /bin/echo "⚡ Performance: $DEPLOYPATH/performance-manifest.json"
    - /bin/echo "🔐 Security: $DEPLOYPATH/security-config.txt"
    - /bin/echo ""
